language: python
sudo: false
cache: pip

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version

script:
- tox -r
after_success:
- codecov

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      python: '2.7'
      env: TOXENV=py27
    - stage: test
      python: '3.4'
      env: TOXENV=py34
    - stage: test
      python: '3.5'
      env: TOXENV=py35
    - stage: test
      python: '3.6'
      env: TOXENV=py36
    - stage: test
      python: '3.6'
      env: TOXENV=docs
    - stage: deploy
      python: '3.6'
      script: bash build_or_deploy.sh build
      after_success: echo after_success
      deploy:
        provider: script
        script: bash build_or_deploy.sh push
        skip_cleanup: true
        on:
          tags: true

notifications:
  email:
    on_failure: always

branches:
  except:
  - "/^noci-.*$/"
